#!/usr/bin/env node
// build.js — the build in Node (a port of build.py, so one runtime builds and tests; the outputs are byte-identical).
//
//   node build.js          tethys.html (single file, everything inlined), dev.html (loads src/*.js separately), src/INDEX.md
//   node build.js --test   the same, then node test/lint.js, node test/physics.js, node test/anim.js, node test/audio.js, node test/snow.js, node test/combat.js, node test/census.js 40 and node test/smoke.js on both tiers; exit 1 on any failure
//
// Build order comes from src/order.txt. src/INDEX.md is generated: every top-level name, its file and line. Do not edit
// INDEX.md by hand; it is rewritten on every build. build.py is kept for the sandbox sessions; keep the two in step.
'use strict';
const fs=require('fs'),path=require('path'),{spawnSync}=require('child_process');
const ROOT=__dirname;
const THREE='<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>\n';
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const write=(p,s)=>fs.writeFileSync(path.join(ROOT,p),s,'utf8');

const ORDER=read('src/order.txt').split('\n').map(l=>l.trim()).filter(l=>l&&!l.startsWith('#'));
const parts={};for(const n of ORDER)parts[n]=read('src/'+n+'.js');

// ---------- the two html files ----------
const shell=read('shell.html');
const bundle=THREE+'<script>\n(function(){\n"use strict";\n'+ORDER.map(n=>parts[n]).join('\n')+'\n})();\n</script>';
write('tethys.html',shell.replace('<!--SCRIPTS-->',()=>bundle)); // a function: the bundle may contain $-patterns a string replacement would expand
const dev=THREE+ORDER.map(n=>'<script src="src/'+n+'.js"></script>\n').join('');
write('dev.html',shell.replace('<!--SCRIPTS-->',()=>dev));

// ---------- the name index ----------
// A small tokenizer: comments and string literals are dropped (the code has no template literals), then top-level declarations
// are the const/let/var/function/class keywords seen at bracket depth 0. Who uses a name is a grep away (`grep -n name src/*.js`).
const TOKEN=/\/\/[^\n]*|\/\*[\s\S]*?\*\/|'(?:\\.|[^'\\\n])*'|"(?:\\.|[^"\\\n])*"|[A-Za-z_$][\w$]*|\d[\w.]*|\S/g;
const KEYWORDS=new Set(['const','let','var','function','class']);
function countNL(s,a,b){let n=0;for(let i=a;i<b;i++)if(s.charCodeAt(i)===10)n++;return n;}
function tokens(src){ // [token, line] pairs with comments and strings removed (a string becomes the placeholder '""')
  const out=[];let line=1,pos=0,m;TOKEN.lastIndex=0;
  while((m=TOKEN.exec(src))!==null){const tok=m[0];line+=countNL(src,pos,m.index);pos=m.index+tok.length;
    if(tok.startsWith('//')||tok.startsWith('/*')){}
    else if(tok[0]==="'"||tok[0]==='"')out.push(['""',line]);
    else out.push([tok,line]);
    line+=countNL(tok,0,tok.length);}
  return out;
}
function topLevel(toks){ // {name: line} for every declaration at depth 0
  const names={};let depth=0,i=0;
  while(i<toks.length){const tok=toks[i][0];
    if('([{'.includes(tok))depth++;
    else if(')]}'.includes(tok))depth--;
    else if(depth===0&&KEYWORDS.has(tok)){
      if(tok==='function'||tok==='class'){const j=(i+1<toks.length&&toks[i+1][0]==='*')?i+2:i+1;if(j<toks.length&&/^[A-Za-z_$]/.test(toks[j][0]))names[toks[j][0]]=toks[j][1];}
      else{let j=i+1,d=0,expect=true; // const a=..., b=...;  declarators are the identifiers after the keyword or after a depth-0 comma
        while(j<toks.length){const t=toks[j][0];
          if(d===0&&t===';')break;
          if('([{'.includes(t))d++;
          else if(')]}'.includes(t)){if(d===0)break;d--;}
          else if(d===0&&t===',')expect=true;
          else if(expect&&/^[A-Za-z_$]/.test(t)){names[t]=toks[j][1];expect=false;}
          else if(expect&&t==='=')expect=false;
          j++;}}
    }
    i++;}
  return names;
}
const defs={};for(const n of ORDER)defs[n]=topLevel(tokens(parts[n]));
const home={};for(const n of ORDER)for(const name of Object.keys(defs[n]))if(!(name in home))home[name]=n;
const escapeRe=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const lines=['# src/INDEX.md — every top-level name and the line it is declared on',
  '',
  'Generated by `python3 build.py`; do not edit. One shared scope: any file may use any name declared in any file',
  '(order only matters for statements that run at load; see `src/order.txt`). To see who uses a name:',
  '`grep -n name src/*.js`. To see which names are unused or undeclared: `node test/lint.js`.',
  ''];
for(const n of ORDER){
  let head=parts[n].split('\n',1)[0];
  head=head.startsWith('//')?head.replace(new RegExp('^//\\s*'+escapeRe(n)+'\\.js\\s*[—-]*\\s*'),'').trim():'';
  lines.push('## '+n+'.js'+(head?' — '+head:''));
  const entries=Object.entries(defs[n]).sort((a,b)=>a[1]-b[1]).filter(([name])=>home[name]===n).map(([name,line])=>'`'+name+'` '+line);
  lines.push(entries.length?entries.join('  '):'(no top-level names)');
  lines.push('');
}
write('src/INDEX.md',lines.join('\n'));
console.log('built tethys.html, dev.html, src/INDEX.md ('+ORDER.length+' files, '+Object.keys(home).length+' top-level names)');

// ---------- tests ----------
if(process.argv.includes('--test')){
  let ok=true;
  const runs=[[['test/lint.js'],{}],[['test/physics.js'],{}],[['test/anim.js'],{}],[['test/audio.js'],{}],[['test/snow.js'],{}],[['test/combat.js'],{}],[['test/census.js','40'],{}],[['test/smoke.js'],{}],[['test/smoke.js'],{TIER:'low'}]];
  for(const [args,env] of runs){
    console.log('\n$ '+Object.entries(env).map(([k,v])=>k+'='+v+' ').join('')+'node '+args.join(' '));
    const r=spawnSync(process.execPath,args,{cwd:ROOT,stdio:'inherit',env:Object.assign({},process.env,env)});
    ok=ok&&r.status===0;
  }
  console.log(ok?'\nALL OK':'\nFAILED');
  process.exit(ok?0:1);
}
