#!/usr/bin/env python3
"""Builds the game and the name index.

  python3 build.py          tethys.html (single file, everything inlined), dev.html (loads src/*.js separately), src/INDEX.md
  python3 build.py --test   the same, then node test/lint.js, node test/physics.js, node test/anim.js, node test/audio.js, node test/snow.js, node test/combat.js, node test/census.js 40, node test/live.js and node test/smoke.js on both tiers; exit 1 on any failure

Build order comes from src/order.txt. src/INDEX.md is generated: every top-level name, its file and line, and which other
files use it. Do not edit INDEX.md by hand; it is rewritten on every build.
"""
import os, re, subprocess, sys
ROOT = os.path.dirname(os.path.abspath(__file__))
THREE = '<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>\n'

def read(p): return open(os.path.join(ROOT, p), encoding='utf-8').read()
def write(p, s): open(os.path.join(ROOT, p), 'w', encoding='utf-8').write(s)

ORDER = [l.strip() for l in read('src/order.txt').split('\n') if l.strip() and not l.strip().startswith('#')]
parts = {n: read('src/%s.js' % n) for n in ORDER}

# ---------- the two html files ----------
shell = read('shell.html')
bundle = THREE + '<script>\n(function(){\n"use strict";\n' + '\n'.join(parts[n] for n in ORDER) + '\n})();\n</script>'
write('tethys.html', shell.replace('<!--SCRIPTS-->', bundle))
dev = THREE + ''.join('<script src="src/%s.js"></script>\n' % n for n in ORDER)
write('dev.html', shell.replace('<!--SCRIPTS-->', dev))

# ---------- the name index ----------
# A small tokenizer: comments and string literals are dropped (the code has no regex or template literals), then top-level
# declarations are the const/let/var/function/class keywords seen at bracket depth 0. Who uses a name is a grep away
# (`grep -n name src/*.js`); an index of that would need scope analysis to be exact, and test/lint.js has it if wanted.
TOKEN = re.compile(r'''//[^\n]*|/\*.*?\*/|'(?:\\.|[^'\\\n])*'|"(?:\\.|[^"\\\n])*"|[A-Za-z_$][\w$]*|\d[\w.]*|\S''', re.S)
KEYWORDS = {'const', 'let', 'var', 'function', 'class'}

def tokens(src):
    """(token, line) pairs with comments and strings removed (a string becomes the placeholder '""')."""
    out, line, pos = [], 1, 0
    for m in TOKEN.finditer(src):
        tok = m.group(0)
        line += src.count('\n', pos, m.start()); pos = m.end()
        if tok.startswith('//') or tok.startswith('/*'):
            pass
        elif tok[0] in '\'"':
            out.append(('""', line))
        else:
            out.append((tok, line))
        line += tok.count('\n')
    return out

def top_level(toks):
    """{name: line} for every declaration at depth 0."""
    names, depth, i = {}, 0, 0
    while i < len(toks):
        tok, line = toks[i]
        if tok in '([{': depth += 1
        elif tok in ')]}': depth -= 1
        elif depth == 0 and tok in KEYWORDS:
            if tok in ('function', 'class'):
                j = i + 2 if i + 1 < len(toks) and toks[i + 1][0] == '*' else i + 1  # function* name
                if j < len(toks) and re.match(r'[A-Za-z_$]', toks[j][0]): names[toks[j][0]] = toks[j][1]
            else:  # const a=..., b=...;  declarators are the identifiers after the keyword or after a depth-0 comma
                j, d, expect = i + 1, 0, True
                while j < len(toks):
                    t = toks[j][0]
                    if d == 0 and t == ';': break
                    if t in '([{': d += 1
                    elif t in ')]}':
                        if d == 0: break
                        d -= 1
                    elif d == 0 and t == ',': expect = True
                    elif expect and re.match(r'[A-Za-z_$]', t): names[t] = toks[j][1]; expect = False
                    elif expect and t in ('=',): expect = False
                    j += 1
        i += 1
    return names

toks = {n: tokens(parts[n]) for n in ORDER}
defs = {n: top_level(toks[n]) for n in ORDER}
home = {}
for n in ORDER:
    for name in defs[n]: home.setdefault(name, n)

lines = ['# src/INDEX.md — every top-level name and the line it is declared on',
         '',
         'Generated by `python3 build.py`; do not edit. One shared scope: any file may use any name declared in any file',
         '(order only matters for statements that run at load; see `src/order.txt`). To see who uses a name:',
         '`grep -n name src/*.js`. To see which names are unused or undeclared: `node test/lint.js`.',
         '']
for n in ORDER:
    head = parts[n].split('\n', 1)[0]
    head = re.sub(r'^//\s*' + re.escape(n) + r'\.js\s*[—-]*\s*', '', head).strip() if head.startswith('//') else ''
    lines.append('## %s.js%s' % (n, (' — ' + head) if head else ''))
    entries = []
    for name, line in sorted(defs[n].items(), key=lambda kv: kv[1]):
        if home[name] != n: continue
        entries.append('`%s` %d' % (name, line))
    lines.append('  '.join(entries) if entries else '(no top-level names)')
    lines.append('')
write('src/INDEX.md', '\n'.join(lines))
print('built tethys.html, dev.html, src/INDEX.md (%d files, %d top-level names)' % (len(ORDER), len(home)))

# ---------- tests ----------
if '--test' in sys.argv:
    ok = True
    for cmd, env in [(['node', 'test/lint.js'], {}), (['node', 'test/physics.js'], {}), (['node', 'test/anim.js'], {}), (['node', 'test/audio.js'], {}), (['node', 'test/snow.js'], {}), (['node', 'test/combat.js'], {}), (['node', 'test/census.js', '40'], {}), (['node', 'test/live.js'], {}), (['node', 'test/live.js'], {'TIER': 'low'}), (['node', 'test/smoke.js'], {}), (['node', 'test/smoke.js'], {'TIER': 'low'})]:
        print('\n$ ' + ' '.join(('%s=%s ' % kv for kv in env.items())) + ' '.join(cmd))
        r = subprocess.run(cmd, cwd=ROOT, env={**os.environ, **env})
        ok = ok and r.returncode == 0
    print('\nALL OK' if ok else '\nFAILED')
    sys.exit(0 if ok else 1)
