// effects.js — the effects list (v11.23, the person's ask): the purely cosmetic systems, each switchable live, on the menu (the word
// at the bottom right, or e) and in play (e; the pointer is released while the list is open and taken back when it closes). Nothing
// here changes the world, the weather or the physics — a shower still falls with its streaks off, the sun still sets with its shadows
// off — only what is drawn. The choices persist in localStorage ('tethys.fx'); FX_DEF is what a fresh browser gets. FX is read where
// each system is drawn: the caustics and the shadows through applyFog → LIGHT_K (atmosphere.js) and updateShadow (scene.js), the
// shafts, the snow, the rain and the cumulus in atmosphere.js, the vignette here (the #vig layer in the shell).
// pixel (v11.38): the caustic and the shadows in world-fixed blocks with hard edges, or smooth (scene.js uPix); off since v11.38.1 (the person prefers the smooth light "at least for now").
// texels (v11.40–41 as part of `pixel`, its own row since v11.41.1 — the person wants to try the textures with the smooth light): every tinted surface in texels fixed to
// the thing it is on, with a pattern per cell (scene.js uTex, PIX_T/PIX_TB, PIXEL.md); off by default.
// texelLight (v11.41.2): with texels on, the light posterised with the colour — since v11.41.3 dithered per cell (a 2×2 Bayer), so the rings round the player's
// light (the person: Morrowind) are checkered bands instead of contours — or, off, the light left smooth and only the albedo in cells (the person: "rainbow
// sherbet") (scene.js uTexL, the note at PIX_GLSL). On by default since v11.41.3; kept to compare.
// cauK (v11.38.1): the caustics' brightness, a slider under the switch, a multiplier on SEA_FOG.cau (atmosphere.js).
// freeLook (v11.77.3; the default since v11.79 — the person, 22 Sep 2026: 'free look should be the default for sure … the game needed those simpler controls and a camera that isn't pulling you like it's a racing game'): the mouse spins the camera round the body, which holds its facing until a movement key is down and then turns toward the camera (player.js); off, the mouse steers the animal and the camera is held within HEAD_MAX of it. The one switch here that is not a drawing.
// camFx (v11.80, the person: "maybe we can remove the camera shake, or make the camera effects something modular you can mess with, like the free camera setting"): the three things that move the camera on their own — the shake when you are hurt, the nudge toward a bite, and the fov kick — off in one row. The steering's own camera is not here: it is `freeLook`.
// A switch is one line to add: a key in FX_DEF, a row in FX_LIST, and the system reading FX.key where it draws.
const FX_LIST=[['freeLook','free look'],['camFx','camera shake'],['caustics','caustics'],['refract','refraction'],['pixel','pixel light'],['texels','texels'],['texelLight','banded light'],['shadows','shadows'],['statics','world shadows'],['ground','ground shadows'],['sharp','sharp shadows'],['shafts','light shafts'],['plight','own light'],['snow','marine snow'],['rain','rain'],['clouds','clouds'],['lumps','near clouds'],['blood','blood'],['debris','debris'],['flush','flush'],['vignette','vignette']];
const FX_DEF={freeLook:true,camFx:true,caustics:true,cauK:1,pixel:false,texels:false,texelLight:true,shadows:Q.tier!=='low',statics:false,ground:false,sharp:false,shafts:true,snow:true,rain:true,clouds:true,lumps:true,blood:true,debris:true,flush:false,vignette:true,plight:true,refract:true,refrK:1}; // shadows: off on the low tier (a phone) until measured there; statics, ground (v11.30): the world's own shadows — the flora, rock and structures, and the terrain — off until measured (scene.js updateShadowS); sharp: both shadow maps at twice the size (scene.js shadowSize)
const FX=Object.assign({},FX_DEF);
const FX_V=79,FX_NEW=['freeLook']; // v11.79: the stored record's version, and the keys whose default must reach a browser that saved its choices before it — free look became the default and a saved 'off' from v11.77.3 would have hidden it. Bump FX_V and list the key when a default changes; every other choice the person has made is kept
(function(){try{const s=window.localStorage&&window.localStorage.getItem('tethys.fx');if(s){const o=JSON.parse(s),old=(o.v|0)<FX_V;for(const k in FX_DEF)if(typeof o[k]===typeof FX_DEF[k]&&!(old&&FX_NEW.indexOf(k)>=0))FX[k]=o[k];}}catch(e){}})();
function fxSave(){try{if(window.localStorage)window.localStorage.setItem('tethys.fx',JSON.stringify(Object.assign({v:FX_V},FX)));}catch(e){}}
const fxEl=document.getElementById('fx'),fxListEl=document.getElementById('fxlist'),vigEl=document.getElementById('vig');
let fxOpen=false;
function fxApply(){vigEl.style.display=FX.vignette?'':'none';pixU.value=FX.pixel?1:0;texU.value=FX.texels?1:0;texLU.value=FX.texelLight?1:0;if(typeof wasAbove==='boolean')applyFog(wasAbove);shadowDirty();} // a switch changes the world map's caster set // the fog's light block reads FX (LIGHT_K); before the first frame applyFog runs on its own
const FX_SLIDERS={caustics:['brightness','cauK',0,2,0.05],refract:['wobble','refrK',0,3,0.05]}; // refract (v11.51): the underside's refraction of the frame (atmosphere.js REFR_*), wobble a multiplier on REFR_K // a slider under a switch (v11.38.1, the person's ask): [label, key, min, max, step]; the key is a number in FX_DEF and persists with the switches
function fxRender(){fxListEl.innerHTML=FX_LIST.map(e=>{let h='<div class="row'+(FX[e[0]]?'':' off')+'" data-k="'+e[0]+'"><span>'+e[1]+'</span><b>'+(FX[e[0]]?'on':'off')+'</b></div>';const s=FX_SLIDERS[e[0]];if(s)h+='<div class="row sl"><span>'+s[0]+'</span><input type="range" data-s="'+s[1]+'" min="'+s[2]+'" max="'+s[3]+'" step="'+s[4]+'" value="'+FX[s[1]]+'"><b>'+FX[s[1]].toFixed(2)+'</b></div>';return h;}).join('');}
function fxToggle(k){if(!(k in FX_DEF))return;FX[k]=!FX[k];fxSave();fxApply();fxRender();}
function fxShow(on){if(on===fxOpen)return;fxOpen=on;fxEl.classList.toggle('on',on);if(on){fxRender();if(mode==='play'&&locked)unlock();}else if(mode==='play'&&!isTouch)tryLock();}
function updateFX(){if(fxOpen&&mode!=='menu'&&mode!=='play')fxShow(false);} // the list closes on the way into the bestiary or the lab (v11.47: the menu's `effects` word is gone — `options` on the menu opens it, menu.js)
fxListEl.addEventListener('input',e=>{const el=e.target;if(!(el.dataset&&el.dataset.s))return;FX[el.dataset.s]=+el.value;el.nextElementSibling.textContent=(+el.value).toFixed(2);fxSave();}); // a slider: live, saved, read where the system draws
fxListEl.addEventListener('click',e=>{let el=e.target;if(el.tagName==='INPUT')return;while(el&&el!==fxListEl&&!(el.dataset&&el.dataset.k))el=el.parentNode;if(el&&el!==fxListEl&&el.dataset&&el.dataset.k)fxToggle(el.dataset.k);});
addEventListener('keydown',e=>{if(e.code==='KeyE'&&(mode==='menu'||mode==='play'))fxShow(!fxOpen);else if(e.code==='Escape'&&fxOpen){fxShow(false);e.preventDefault();}}); // the default prevented: menu.js's esc (play to the menu) runs after this and stands down
document.addEventListener('pointerlockchange',()=>{if(fxOpen&&document.pointerLockElement===canvas)fxShow(false);}); // a click on the canvas took the pointer back: the list is done with
fxApply();
